### PR TITLE
MIKE Core Release 2022 + Read/WriteDfs0DataDouble

### PR DESCRIPTION
**Pull request by JesperGr**
Update for Release 2022 of MIKE Core. Added native support for Read/WriteDfs0DataDouble for Linux as well.

### CODE REVIEW

**Review by ecomodeller — APPROVED** [review]

**Review by jsmariegaard — APPROVED** [review]
Looks good - no comments

**Comment by ecomodeller** [comment]
This has a huge improvement on the Dfs0 performance on Linux as shown by the [MIKEIO Perf test](https://github.com/DHI/mikeio/actions/workflows/perf_test.yml)

Before merging this PR:
image

After this PR:
image

**Comment by jsmariegaard** [comment]
🥳 :shipit:

**Comment by jsmariegaard** [comment]
Why is it now twice as fast on Linux as on windows 😕  ?

**Pull request merged**
